---
title: "SR205_Question_21"
output: html_notebook
---



```{r}
library(edgeR)
library(limma)
library(ggplot2)
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(viridis)
library(circlize)

```

Please note that this does **not** load the data nor does the normalization steps! This just shows 1. getting top genes and then plotting the heatmap. This code was practically run in the SR205_assignment2.Rmd where the data is loaded


## Question 21
```{r}

# first filter results table for top 20 genes by log2FC
top_genes <- res[order(res$log2FoldChange, decreasing = T), ] %>% as.data.frame()

# next filter and remove genes with pvalue less than 0.01
top_genes <- filter(top_genes, top_genes$padj < 0.01)

# now only keep top 20 first of the basal and then of the luminal
top_genes <- c(rownames(tail(top_genes,20)) , rownames(top_genes)[1:20])

top_genes

```





```{r}
# how we can filter our edgeR matrix to only keep the top 20 genes
mat <- cpm_log[top_genes,]
colnames(mat) <- group

head(mat)
```



```{r}
# Generate cols to use for next part
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
```



```{r}
#set annotation for heatmap
ann <- data.frame(sample_info$CellType, sample_info$Status)
colnames(ann) <- c("CellType", "Status")

ct.n <- length(levels(as.factor(sample_info$CellType)))
ct.col <- sample(col_vector, ct.n)
names(ct.col) = levels(as.factor(sample_info$CellType))

status.n <- length(levels(as.factor(sample_info$Status)))
status.col <- sample(col_vector, status.n)
names(status.col) = levels(as.factor(sample_info$Status))

ann.cols <- list(
  "CellType" = ct.col,
  'Status' = status.col
)

# Plug this into Complex heatmap in the next step
colAnn <- HeatmapAnnotation(df = ann,
                            which = 'column',
                            col = ann.cols,
                            annotation_width = unit(c(1, 4), 'cm'),
                            gap = unit(1, 'mm'),
                            show_legend = T)


```

```{r, fig.height=8, fig.width=8}

# scale for heatmap
col_fun <- colorRamp2(seq(-3,14, length.out = 100), plasma(100))

hm <- Heatmap(mat,
        # Plot title
        column_title = "Top Genes Expressed in Basal vs Luminal",
        column_title_gp = gpar(fontsize = 20, fontface = "bold"),
        
        # heatmap color
        col = col_fun, 
        
        # Column Parameters
        column_names_side = 'top',
        show_column_dend = F,
        column_names_rot = 30,
        cluster_columns = F,
        column_names_gp = gpar(fontsize = 8),
        
        
        
        # Row Parameters
        row_title = " genes",
        show_row_dend = T,
        cluster_rows = F,
        show_row_names = T,
        row_dend_side = 'right',
        row_dend_width = unit(10,'mm'),
        row_names_gp = gpar(fontsize = 8),
        row_names_side = 'left',
        
        # Annotations
        top_annotation=colAnn,
        
        # Legend
        show_heatmap_legend = T,
        # name
        name = "log2"
)

png("Assignment2_question21_heatmap.png")
hm
dev.off()


hm
```


